apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: node-claim
  name: node-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
status: {}
